
    <link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link type="text/css" rel="stylesheet" href="css/materialize.min.css" media="screen,projection" />
    <link rel="stylesheet" type="text/css" href="css/styles.css">
    <!--Let browser know website is optimized for mobile-->
    <meta name="viewport" content="width=device-width, initial-scale=1.0" /> 

    <body>
      <div class="row full-height">
        <div class="sidebar-fixed col s0 m3 l2 hide-on-small-only z-depth-2">
          <div class="nav-wrapper">
            <!--<ul class="side-nav">-->
            <ul>
              <li><a class="waves-effect waves-teal btn-flat btn-large" href="/profile">profile</a></li>
              <li><a class="waves-effect waves-teal btn-flat btn-large" href="/pantry">pantry</a></li>
              <li><a class="waves-effect waves-teal btn-flat btn-large" href="/feed">feed</a></li>
              <li><a class="waves-effect waves-teal btn-flat btn-large" href="/search">search</a></li>
            </ul>
          </div>
        </div>
        <div class="page-content col s12 m9 l10">
          
          <nav class="half-nav row">
            <div class="nav-wrapper">
              <a href="#!" class="brand-logo right">Logo</a>
              <a href="#" data-activates="mobile-demo" class="button-collapse hide-on-med-and-up"><i class="material-icons">menu</i></a>
              <ul class="side-nav" id="mobile-demo">
                <li><a class="waves-effect waves-teal btn-flat btn-large" href="/profile"><i class="material-icons">perm_identity</i>profile</a></li>
                <li><a class="waves-effect waves-teal btn-flat btn-large" href="/pantry"><i class="material-icons">shopping_cart</i>pantry</a></li>
                <li><a class="waves-effect waves-teal btn-large btn-flat" href="/feed"><i class="material-icons">dashboard</i>feed</a></li>
                <li><a class="waves-effect waves-teal btn-large btn-flat" href="/search"><i class="material-icons">search</i>search</a></li>
              </ul>
            </div>
          </nav>
          
          <div class="container">
            <div class="row">
              <div class="col s6 m4 l4">
                <div class="card">
                  <div class="card-image">
                    <img src="img/cheese-stuffed-artichoke-bottosms.jpg">
                    <!--<span class="card-title">Card Title</span>-->
                  </div>
                  <div class="card-action">
                    <p>Cheese-Stuffed Artichoke Bottoms</p>
                  </div>
                </div>
              </div>
              <div class="col s6 m4 l4">
                <div class="card">
                  <div class="card-image">
                    <img src="img/chicken-florentine.jpg">
                    <!--<span class="card-title">Card Title</span>-->
                  </div>
                  <div class="card-action">
                    <p>Chicken Florentine</p>
                  </div>
                </div>
              </div>
              <div class="col s6 m4 l4">
                <div class="card">
                  <div class="card-image">
                    <img src="img/grilled-cheese-tomato-bisc-shooters.jpg">
                    <!--<span class="card-title">Card Title</span>-->
                  </div>
                  <div class="card-action">
                    <p>Grilled Cheese Tomato Bisc Shooters</p>
                  </div>
                </div>
              </div>
              <div class="col s6 m4 l4">
                <div class="card">
                  <div class="card-image">
                    <img src="img/thai.jpg">
                    <!--<span class="card-title">Card Title</span>-->
                  </div>
                  <div class="card-action">
                    <p>Pepper Steak Eggrolls</button>
                  </div>
                </div>
              </div>
              <div class="col s6 m4 l4">
                <div class="card">
                  <div class="card-image">
                    <img src="img/mushroom-herb-turnovers.jpg">
                    <!--<span class="card-title">Card Title</span>-->
                  </div>
                  <div class="card-action">
                    <p>Mushroom Herb Turnovers</p>
                  </div>
                </div>
              </div>        
            </div>
            <div class="fixed-action-btn">
              <a class="btn-floating btn-large teal" href="#!">
                <i class="large material-icons">add</i>
              </a>
              <!--<ul>
                <li><a class="btn-floating red"><i class="material-icons">insert_chart</i></a></li>
                <li><a class="btn-floating yellow darken-1"><i class="material-icons">format_quote</i></a></li>
                <li><a class="btn-floating green"><i class="material-icons">publish</i></a></li>
                <li><a class="btn-floating blue"><i class="material-icons">attach_file</i></a></li>
              </ul>-->
            </div>
          </div>
        </div>
      </div>
      <div class="container page-name">
        <div class="row">
          <div class="page-content">
            
          </div>
        </div>
      </div>
      
      
      
      
      <!--Import jQuery before materialize.js-->
      <script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
      <script type="text/javascript" src="css/js/materialize.min.js"></script>
      <script type="text/javascript"> $(".button-collapse").sideNav(); </script>
    </body>