<link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
<link type="text/css" rel="stylesheet" href="css/materialize.min.css" media="screen,projection" />
<link rel="stylesheet" type="text/css" href="css/styles.css">
<!--Let browser know website is optimized for mobile-->
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<body>
  <div class="row full-height">
    <!-- landscape fixed nav -->
    <div class="sidebar-fixed col s0 m3 l2 hide-on-small-only z-depth-2">
      <div class="nav-wrapper">
        <ul>
          <li><img class="corner-logo" src="img/socialcart-lockup.png"></li>
          <li>
            <a class="waves-effect waves-teal btn-flat" href="/profile">
              <i class="material-icons">perm_identity</i>
              profile
            </a>
          </li>
          <li>
            <a class="waves-effect waves-teal btn-flat" href="/pantry">
              <i class="material-icons">shopping_cart</i>
              pantry
            </a>
          </li>
          <li>
            <a class="waves-effect waves-teal btn-flat" href="/feed">
              <i class="material-icons">dashboard</i>
              feed
            </a>
          </li>
          <li>
            <a class="waves-effect waves-teal btn-flat" href="/search">
              <i class="material-icons">search</i>
              search
            </a>
          </li>
        </ul>
      </div>
    </div>

    <div class="page-content col s12 m9 l10">
      
      <nav class="half-nav row">
        <div class="nav-wrapper">
          <a href="#!" class="brand-logo right">Page Name</a>
          <a href="#" data-activates="mobile-demo" class="button-collapse hide-on-med-and-up"><i class="material-icons">menu</i></a>
          <ul class="side-nav" id="mobile-demo">
            <li><img class="corner-logo" src="img/socialcart-lockup.png"></li>
            <li><a class="waves-effect waves-teal btn-flat btn-large" href="/profile"><i class="material-icons">perm_identity</i>profile</a></li>
            <li><a class="waves-effect waves-teal btn-flat btn-large" href="/pantry"><i class="material-icons">shopping_cart</i>pantry</a></li>
            <li><a class="waves-effect waves-teal btn-large btn-flat" href="/feed"><i class="material-icons">dashboard</i>feed</a></li>
            <li><a class="waves-effect waves-teal btn-large btn-flat" href="/search"><i class="material-icons">search</i>search</a></li>
          </ul>
        </div>
      </nav>
      <div class="container">
        
      </div>
    </div>
  </div>
  <div class="container page-name">
    <div class="row">
      
      <div class="page-content">
        
      </div>
    </div>
  </div>
  
  
  
  
  <!--Import jQuery before materialize.js-->
  <script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
  <script type="text/javascript" src="css/js/materialize.min.js"></script>
  <script type="text/javascript"> $(".button-collapse").sideNav(); </script>
</body>