<link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
<link type="text/css" rel="stylesheet" href="css/materialize.min.css" media="screen,projection" />
<link rel="stylesheet" type="text/css" href="css/styles.css">
<!--Let browser know website is optimized for mobile-->
<meta name="viewport" content="width=device-width, initial-scale=1.0" />

<body>    
    <div class="flex sign-page container">
        <div class="window row">
            <div class="sign-window col s12 m6 l6 z-depth-4 offset-m3 offset-l3">
              <form class="container" method="post">
                  <div class="row header-img">
                      <!--<div class="col s4 m3 l4 logo" style=" background: url('images/cart-icon.png')"> </div>
                      <div class="col s8 m9 l8 title"><h3>SocialCart</h3></div>-->
                      <img src="img/socialcart-lockup.png">
                  </div>
                <div class="row account-field">
                  <div class="input-field col s12"> <i class="material-icons prefix">visibility</i>
                    <input id="perm" name="name" type="text" class="validate">
                    <label for="icon_prefix">Name</label>
                  </div>
                </div>
                <div class="row account-field">
                  <div class="input-field col s12"> <i class="material-icons prefix">email</i>
                    <input id="perm" name="email" type="text" class="validate">
                    <label for="icon_prefix">Email</label>
                  </div>
                </div>
                <div class="row account-field">
                  <div class="input-field col s12"> <i class="material-icons prefix">account_circle</i>
                    <input id="perm" name="username" type="text" class="validate">
                    <label for="icon_prefix">Username</label>
                  </div>
                </div>
                <div class="row phone-field">
                  <div class="input-field col s12"> <i class="material-icons prefix">lock</i>
                    <input id="password" name="password" type="password" class="validate">
                    <label for="lock">Password</label>
                  </div>
                </div>
                <div class="row">
                  <button type="submit" class="waves-effect waves-light btn">Sign up</button>
                  </div>
              </form>
            </div>
        </div>
    </div>
  <!--Import jQuery before materialize.js-->
  <script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
  <script type="text/javascript" src="css/js/materialize.min.js"></script>
</body>

