
    <link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link type="text/css" rel="stylesheet" href="css/materialize.min.css" media="screen,projection" />
    <link rel="stylesheet" type="text/css" href="css/styles.css">
    <!--Let browser know website is optimized for mobile-->
    <meta name="viewport" content="width=device-width, initial-scale=1.0" /> 

    <body>
      <div class="row full-height">
        <div class="sidebar-fixed col s0 m3 l2 hide-on-small-only z-depth-2">
          <div class="nav-wrapper">
            <!--<ul class="side-nav">-->
            <ul>
              <li><a class="waves-effect waves-teal btn-flat btn-large" href="/profile">profile</a></li>
              <li><a class="waves-effect waves-teal btn-flat btn-large" href="/pantry">pantry</a></li>
              <li><a class="waves-effect waves-teal btn-flat btn-large" href="/feed">feed</a></li>
              <li><a class="waves-effect waves-teal btn-flat btn-large" href="/search">search</a></li>
            </ul>
          </div>
        </div>
        <div class="page-content col s12 m9 l10">
          
          <nav class="half-nav row">
            <div class="nav-wrapper">
              <a href="#!" class="brand-logo right">Peppered Steak Eggrolls</a>
              <a href="#" data-activates="mobile-demo" class="button-collapse hide-on-med-and-up"><i class="material-icons">menu</i></a>
              <ul class="side-nav" id="mobile-demo">
                <li><a class="waves-effect waves-teal btn-flat btn-large" href="/profile"><i class="material-icons">perm_identity</i>profile</a></li>
                <li><a class="waves-effect waves-teal btn-flat btn-large" href="/pantry"><i class="material-icons">shopping_cart</i>pantry</a></li>
                <li><a class="waves-effect waves-teal btn-large btn-flat" href="/feed"><i class="material-icons">dashboard</i>feed</a></li>
                <li><a class="waves-effect waves-teal btn-large btn-flat" href="/search"><i class="material-icons">search</i>search</a></li>
              </ul>
            </div>
          </nav>
          
          <div class="row recipe-page">

							<div class="recipe-background" style="background-image: url('images/thai.jpg')">
								
							</div>

            
						<div class="container">
							<h5>Made Recently</h5><hr>
						<div class="chip">
							<img src="images/profile1.jpg" alt="Contact Person">
							Rick Stryker
						</div>
											<div class="chip">
							<img src="images/profile2.jpg" alt="Contact Person">
							Apollo Stephensen
						</div>
						</div>
						
						
						<div class="container">
							<h5>Grocery List</h5><hr>
						<div class="chip">
    Green Onion
    <i class="close material-icons">close</i>
  </div>
							<div class="chip">
    Sesame Oil
    <i class="close material-icons">close</i>
  </div>
							<div class="chip">
    Cabbage
    <i class="close material-icons">close</i>
  </div>
							<div class="chip">
    Chicken
    <i class="close material-icons">close</i>
  </div>
						</div>
						
						
						<div class="container">
							<h5>Ingredients</h5><hr>
							<p>2 tablespoons soy sauce</p>
							<p>2 tablespoons sherry</p>
							<p>1/2 teaspoon salt</p>
							<p>1/2 teaspoon ground black pepper</p>
							<p>2 quarts vegetable oil</p>
							<p>1 onion, thinly sliced</p>
							<p>1/2 teaspoon dried minced garlic</p>
							<p>2 tablespoons soy sauce</p>
							<p>1 teaspoon ground ginger</p>
							<p>1 large head cabbage (shredded)</p>
							<p>16 egg roll wrappers</p>
							<p>1 green pepper</p>
							<p>1 jalepeno pepper</p>
						</div>
						
						
						
          </div>
        </div>
      </div>
      <div class="container page-name">
        <div class="row">
          <div class="page-content">
            
          </div>
        </div>
      </div>
      
      
      
      
      <!--Import jQuery before materialize.js-->
      <script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
      <script type="text/javascript" src="css/js/materialize.min.js"></script>
      <script type="text/javascript"> $(".button-collapse").sideNav(); 
			
			</script>
    </body>